"""

    We wish to test the batch generation process by generating batches
    Here we print out 20 conversations (each a message and output pair) in four batches.
    The result is in the file 'MyBatchSample.txt'

"""



from batch_generation import  *
from testData import convertList2sentence
batch_size = 4


"""
We open our dataset and unpack the dictionary and the conversations
"""
data_store = ''
file_name = ''
data_path = os.path.join(data_store, file_name)
word2id, id2word, training_data = loadData(data_path)
training_data = training_data[0:20]
batches = generateBatches(training_data, batch_size)


"""
We write 20 conversations, generated by batch of four.
"""
writer2 = open("./MyBatchSample.txt", "w")
for c, nextBatch in enumerate(batches):
    assert len(nextBatch.inputMsgIDs) == batch_size
    assert len(nextBatch.outputResponseIDs) == batch_size
    writer2.write('Batch %d with %d examples \n' % (c, len(nextBatch.inputMsgIDs)))
    for k in range(batch_size):
        input = 'Input: ' + convertList2sentence(nextBatch.inputMsgIDs[k])
        output = 'Output:' + convertList2sentence(nextBatch.outputResponseIDs[k])
        writer2.write(input + "    ||    " + output + '\n')
    writer2.write('==================================\n')
writer2.close()

"""
Now we can inspect the file MyBatchSample.txt to observe the batch generation
"""